### ISSUE TITLE
Invalid JSON String

### ISSUE THREAD

**Issue by mattmueller** [pengwynn/gowalla#1]
Haven't tracked this all the way down but when trying to use list spots or featured spots I consistently get thrown an invalid json string:

Crack::ParseError: Invalid JSON string
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/crack-0.1.6/lib/crack/json.rb:14:in `parse'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:116:in`json'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:136:in `send'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:136:in`parse_supported_format'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:103:in `parse'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:66:in`call'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/request.rb:160:in `parse_response'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/request.rb:155:in`handle_response'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/request.rb:60:in `perform'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty.rb:243:in`perform_request'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty.rb:195:in `get'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/gowalla-0.1.2/lib/gowalla/client.rb:81:in`list_spots'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/gowalla-0.1.2/lib/gowalla/client.rb:85:in `featured_spots'
    from (irb):3

**Comment by pengwynn** [comment]
Hi, Matt,

How are you authenticating. I just noticed the readme includes api_key three times instead of api_key, username, password....

**Comment by mattmueller** [comment]
I was authenticating with u/p/api key.  All of the other methods seem to work except for anything that depends on list_spots (so that included featured spots for example).  It seems like it definitely "should" work as the following is working fine (used it as a replacement for the time being) even without authenticating:

<pre>
results = Hashie::Mash.new(HTTParty.get("http://api.gowalla.com/spots.json?lat=XYZ&lng=ABC&radius=50"))
</pre>

**Comment by pengwynn** [comment]
Hmmm, working for me in the new release last night: c.list_spots(:lat => 30.2697, :lng => -97.7494, :radius => 50)

**Comment by mattmueller** [comment]
Wow, not sure what is different this time but I just tried again and it is indeed working now...sorry to waste your time.
