### ISSUE TITLE
Update to use Faraday 0.6.1

### ISSUE THREAD

**Issue by MikeEmery** [pengwynn/gowalla#17]
Previous to Faraday 0.6.1 it doesn't properly set the ca_path variable for OpenSSL.  I'm using the Gowalla gem in my project and trying to update to Faraday 0.6.1 but since the Gowalla gem has a fixed dependency on 0.5 I'm stuck.

Background information is available in this stackoverflow thread.  http://stackoverflow.com/questions/3977303/omniauth-facebook-certificate-verify-failed

**Comment by ehutzelman** [comment]
Having a few issues with the tests after updating to latest versions, working on it...

**Comment by ehutzelman** [comment]
ok, should be good to go now with new version of gem.
