### ISSUE TITLE
NameError: uninitialized constant Gowalla

### ISSUE THREAD

**Issue by yraffah** [pengwynn/gowalla#2]
I have successfully installed your wrapper on my Mac OS X 10.6:

$ gem install gowalla
WARNING:  Installing to ~/.gem since /Library/Ruby/Gems/1.8 and
      /usr/bin aren't both writable.
When you HTTParty, you must party hard!
Successfully installed hashie-0.2.0
Successfully installed crack-0.1.6
Successfully installed httparty-0.5.2
Successfully installed gowalla-0.1.3
4 gems installed
Installing ri documentation for hashie-0.2.0...
Installing ri documentation for crack-0.1.6...
Installing ri documentation for httparty-0.5.2...
Installing ri documentation for gowalla-0.1.3...
Installing RDoc documentation for hashie-0.2.0...
Installing RDoc documentation for crack-0.1.6...
Installing RDoc documentation for httparty-0.5.2...
Installing RDoc documentation for gowalla-0.1.3...

But when I try the following I get that error message:

$ irb 

> > gowalla = Gowalla::Client.new(:username => 'yraffah', :password => 'mypassword', :api_key => 'my_api_key')
> > NameError: uninitialized constant Gowalla
> >     from (irb):1
> > exit

I have also tried the test_gowalla.rb and here is what I got:

$ ruby .gem/ruby/1.8/gems/gowalla-0.1.3/test/test_gowalla.rb 
.gem/ruby/1.8/gems/gowalla-0.1.3/test/test_gowalla.rb:1:in `require': no such file to load -- helper (LoadError)
    from .gem/ruby/1.8/gems/gowalla-0.1.3/test/test_gowalla.rb:1

Any idea of what can be wrong?

**Comment by yraffah** [comment]
Sorry if this is wasting your time as I'm newbie in Ruby but I saw your thread on gowalla-developers and thought if playing with it a bit!

**Comment by pengwynn** [comment]
Hey there. Normally I install gems with sudo to avoid those warnings, but it looks like your gem was installed anyway. Looks like you're missing a couple of require statements:

```
$ irb
>> require 'rubygems'
>> require 'gowalla'
>> gowalla = Gowalla::Client.new(:username => 'yraffah', :password => 'mypassword', :api_key => 'my_api_key')
```
