### ISSUE TITLE
Crack::ParseError: Invalid JSON string

### ISSUE THREAD

**Issue by mattmueller** [pengwynn/gowalla#3]
So all of a sudden I've started getting errors relating to crack being able to parse a spot request.  As far as I can tell this ONLY effects spot requests.  Example below, any idea what is going on?

<pre>
irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'gowalla'
=> true
irb(main):003:0> g = Gowalla::Client.new
=> #<Gowalla::Client:0x9f2de70 @username=nil>
irb(main):004:0> g.spot(90456)
Crack::ParseError: Invalid JSON string
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/crack-0.1.6/lib/crack/json.rb:14:in `parse'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:116:in `json'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:136:in `send'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:136:in `parse_supported_format'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:103:in `parse'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/parser.rb:66:in `call'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/request.rb:160:in `parse_response'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/request.rb:155:in `handle_response'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty/request.rb:60:in `perform'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty.rb:243:in `perform_request'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/httparty-0.5.2/lib/httparty.rb:195:in `get'
    from /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/gowalla-0.1.3/lib/gowalla/client.rb:76:in `spot'
    from (irb):4
irb(main):005:0> HTTParty
=> HTTParty
irb(main):006:0> HTTParty.get('http://api.gowalla.com/spots/90456.json')
=> {"address"=>{"region"=>"CA", "locality"=>"Newport Beach"}, "name"=>"Sharkeez", "checkins_count"=>18, "created_at"=>"2009-11-10T00:46:58Z", "twitter_username"=>nil, "image_url"=>"http://static.gowalla.com/categories/130-standard.png", "max_items_count"=>10, "radius_meters"=>50, "creator"=>{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/14245-standard.jpg?1259446826", "url"=>"/users/14245", "last_name"=>"Davis", "first_name"=>"Peter"}, "trending_level"=>0, "websites"=>[], "url"=>"/spots/90456", "users_count"=>15, "checkins_url"=>"/checkins?spot_id=90456", "map_bounds"=>{"south"=>nil, "north"=>nil, "west"=>nil, "east"=>nil}, "lng"=>-117.92792495, "spot_categories"=>[{"name"=>"Sports Bar", "url"=>"/categories/130"}], "list_image_url_320"=>nil, "founders"=>[{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/142019-standard.jpg?1272317519", "url"=>"/users/142019", "last_name"=>"Herrick", "first_name"=>"Brooke"}, {"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/4685-standard.jpg?1267488622", "url"=>"/users/4685", "last_name"=>"Wilkins", "first_name"=>"Brian"}, {"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/5889-standard.jpg?1257455518", "url"=>"/users/5889", "last_name"=>"Moen", "first_name"=>"Michael"}, {"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/14245-standard.jpg?1259446826", "url"=>"/users/14245", "last_name"=>"Davis", "first_name"=>"Peter"}], "items_url"=>"/spots/90456/items", "items_count"=>4, "photos_url"=>"/spots/90456/photos", "description"=>"", "strict_radius"=>false, "last_checkins"=>[{"created_at"=>"2010-05-04T02:35:09Z", "url"=>"/checkins/7989531", "type"=>"checkin", "user"=>{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/132416-standard.jpg?1267410749", "url"=>"/users/132416", "last_name"=>"Lambrakis", "first_name"=>"Mike"}, "message"=>"Going to the bathroom"}, {"created_at"=>"2010-05-04T02:32:53Z", "url"=>"/checkins/7989477", "type"=>"checkin", "user"=>{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/142019-standard.jpg?1272317519", "url"=>"/users/142019", "last_name"=>"Herrick", "first_name"=>"Brooke"}, "message"=>""}, {"created_at"=>"2010-04-25T02:44:30Z", "url"=>"/checkins/7468966", "type"=>"checkin", "user"=>{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/1152-standard.jpg?1239999453", "url"=>"/users/1152", "last_name"=>"McClure", "first_name"=>"Kari"}, "message"=>""}, {"created_at"=>"2010-04-24T20:01:07Z", "url"=>"/checkins/7444697", "type"=>"checkin", "user"=>{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/1159-standard.jpg?1240006980", "url"=>"/users/1159", "last_name"=>"Webb", "first_name"=>"Shannon"}, "message"=>""}, {"created_at"=>"2010-04-16T07:02:39Z", "url"=>"/checkins/6915773", "type"=>"checkin", "user"=>{"image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/146485-standard.jpg?1271446838", "url"=>"/users/146485", "last_name"=>"Chen", "first_name"=>"Steve"}, "message"=>""}], "activity_url"=>"/spots/90456/events", "top_10"=>[{"checkins_count"=>"2", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/1152-standard.jpg?1239999453", "url"=>"/users/1152", "last_name"=>"McClure", "first_name"=>"Kari"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/132416-standard.jpg?1267410749", "url"=>"/users/132416", "last_name"=>"Lambrakis", "first_name"=>"Mike"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/142019-standard.jpg?1272317519", "url"=>"/users/142019", "last_name"=>"Herrick", "first_name"=>"Brooke"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/1159-standard.jpg?1240006980", "url"=>"/users/1159", "last_name"=>"Webb", "first_name"=>"Shannon"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/146485-standard.jpg?1271446838", "url"=>"/users/146485", "last_name"=>"Chen", "first_name"=>"Steve"}, {"checkins_count"=>"1", "image_url"=>"http://gowalla.com/images/default-user.jpg", "url"=>"/users/214810", "last_name"=>"Strohm", "first_name"=>"Aj"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/127568-standard.jpg?1266947968", "url"=>"/users/127568", "last_name"=>"Won", "first_name"=>"Andrew"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/6596-standard.jpg?1268798367", "url"=>"/users/6596", "last_name"=>"Lopez", "first_name"=>"David"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/90070-standard.jpg?1267163583", "url"=>"/users/90070", "last_name"=>"Fontanella", "first_name"=>"Jennifer"}, {"checkins_count"=>"1", "image_url"=>"http://s3.amazonaws.com/static.gowalla.com/users/4685-standard.jpg?1267488622", "url"=>"/users/4685", "last_name"=>"Wilkins", "first_name"=>"Brian"}], "lat"=>33.6084873667, "photos_count"=>0}
</pre>

**Comment by mattmueller** [comment]
Strike that, I'm getting it when trying to list spots as well.  So maybe anything dealing with spots is the problem?

**Comment by pengwynn** [comment]
i think they changed the accepts header serverside. I think i fixed in 0.1.4, can you pull down and test?

**Comment by mattmueller** [comment]
Yep, that seemed to do it for me.  Thanks for the quick turnaround :)
