### ISSUE TITLE
Friends_events no longer functioning

### ISSUE THREAD

**Issue by mattmueller** [pengwynn/gowalla#4]
Hate to open another issue but the friends_events call has stopped functioning as well.  I think they may have changed how this is accessed recently but I'm not sure:

<pre>
>> g = Gowalla::Client.new(:username => 'XXX', :password => 'YYY', :api_key => 'ZZZ')

>> g.friends_events
NoMethodError: undefined method `activity' for nil:NilClass
</pre>

**Comment by pengwynn** [comment]
This was due to API flux and has been fixed. Thanks.
