### ISSUE TITLE
faraday-middleware dependency recently changed to faraday_middleware

### ISSUE THREAD

**Issue by jeffarena** [pengwynn/gowalla#8]
'sudo gem install gowalla' now fails, after a recent commit to faraday_middleware (previously faraday-middleware) that changed the gem name.  'sudo gem install faraday-middleware' fails as it cannot locate the gem due to today's name change.

**Comment by pengwynn** [comment]
yup, sorry, working on a fix...

**Comment by jeffarena** [comment]
cool, thanks.  appreciate the quick response!

**Comment by ehutzelman** [comment]
the fix is in, gowalla gem 0.4.0 should be available with the updated reference

**Comment by jeffarena** [comment]
awesome, thanks for the quick turnaround!

**Comment by krsmurata** [comment]
Hi Wynn, seems that this gem dependency is having an identity crisis :)

now it's name is faraday_middleware back again..

http://rubygems.org/gems/faraday_middleware
http://github.com/pengwynn/faraday_middleware

**Comment by pengwynn** [comment]
Yes, that's what it should be. Where are you seeing differently?

**Comment by krsmurata** [comment]
Ops, sorry Wynn, it was some remains on my Gemfile.lock, it's working as expected.
